name: bullmq

include:
  - services/cache/compose.yml
  - services/queues/compose.yml

volumes:
  cache-data:
    driver: local
    name: cache-data
  queues-data:
    driver: local
    name: queues-data

networks:
  bullmq-network:
    driver: bridge
    name: bullmq-network
