name: bullmq

include:
  - services/caching/compose.yml

volumes:
  cache-data:
    driver: local
    name: cache-data
  bullmq-data:
    driver: local
    name: bullmq-data

networks:
  bullmq-network:
    driver: bridge
    name: bullmq-network
