services:
  cache:
    container_name: cache
    image: redis:alpine3.23
    restart: unless-stopped
    env_file: .env.${ENV:-local}
    command: >
      sh -c "redis-server
      --requirepass \"$$REDIS_PASSWORD\"
      --maxmemory 512mb"
    networks:
      - bullky-network
    volumes:
      - bullky-cache-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD --no-auth-warning ping | grep -q PONG"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5
