services:
  queues:
    env_file: .env.local
    container_name: queues
    image: redis:alpine3.23
    restart: unless-stopped
    command: >
      sh -c "redis-server
      --requirepass \"$$REDIS_PASSWORD\"
      --protected-mode yes
      --appendonly yes
      --rename-command FLUSHALL \"\"
      --rename-command FLUSHDB \"\""
    ports:
      - "6379:6379"
    networks:
      - bullmq-network
    volumes:
      - queues-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD --no-auth-warning ping | grep -q PONG"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5